<?xml version="1.0" encoding="utf-8"?><Database Name="pos_admin" Class="POSDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-CVOMG1OH;Initial Catalog=pos_admin;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="pos_adminConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.articulo" Member="articulo">
    <Type Name="articulo">
      <Column Name="cod_barras" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cod_asociado" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="id_clasificacion" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="cod_interno" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion_corta" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cantidad_um" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="id_unidad" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="id_proveedor" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="precio_compra" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="utilidad" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="precio_venta" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_articulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="stock" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="stock_min" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="stock_max" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="iva" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="kit_fecha_ini" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="kit_fecha_fin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="articulo_disponible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="kit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="puntos" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="last_update_inventory" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="cve_producto" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="articulo_articulo" Member="articulo2" ThisKey="cod_barras" OtherKey="cod_asociado" Type="articulo" />
      <Association Name="articulo_compra_articulo" Member="compra_articulo" ThisKey="cod_barras" OtherKey="cod_barras" Type="compra_articulo" />
      <Association Name="articulo_inventario_captura" Member="inventario_captura" ThisKey="cod_barras" OtherKey="cod_barras" Type="inventario_captura" />
      <Association Name="articulo_orden_articulo" Member="orden_articulo" ThisKey="cod_barras" OtherKey="cod_anexo" Type="orden_articulo" />
      <Association Name="articulo_orden_articulo1" Member="orden_articulo1" ThisKey="cod_barras" OtherKey="cod_barras" Type="orden_articulo" />
      <Association Name="articulo_articulo" Member="articulo1" ThisKey="cod_asociado" OtherKey="cod_barras" Type="articulo" IsForeignKey="true" />
      <Association Name="proveedor_articulo" Member="proveedor" ThisKey="id_proveedor" OtherKey="id_proveedor" Type="proveedor" IsForeignKey="true" />
      <Association Name="unidad_medida_articulo" Member="unidad_medida" ThisKey="id_unidad" OtherKey="id_unidad" Type="unidad_medida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.compra" Member="compra">
    <Type Name="compra">
      <Column Name="id_compra" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_proveedor" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="no_factura" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fecha_compra" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id_pedido" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="cancelada" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fecha_cancelacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="no_entrada" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="observaciones" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="compra_compra_articulo" Member="compra_articulo" ThisKey="id_compra" OtherKey="id_compra" Type="compra_articulo" />
      <Association Name="proveedor_compra" Member="proveedor" ThisKey="id_proveedor" OtherKey="id_proveedor" Type="proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.compra_articulo" Member="compra_articulo">
    <Type Name="compra_articulo">
      <Column Name="id_compra" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cod_barras" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="num_articulo" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cant_cja" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="cant_pza" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="precio_compra" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="no_captura" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="no_entrega" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Association Name="articulo_compra_articulo" Member="articulo" ThisKey="cod_barras" OtherKey="cod_barras" Type="articulo" IsForeignKey="true" />
      <Association Name="compra_compra_articulo" Member="compra" ThisKey="id_compra" OtherKey="id_compra" Type="compra" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ctrl_errores" Member="ctrl_errores">
    <Type Name="ctrl_errores">
      <Column Name="id_error" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fecha_log" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.inventario_captura" Member="inventario_captura">
    <Type Name="inventario_captura">
      <Column Name="id_captura" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_inventario_fisico" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="num_captura" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cod_barras" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_captura" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="cant_cja" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="cant_pza" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="upload" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="articulo_inventario_captura" Member="articulo" ThisKey="cod_barras" OtherKey="cod_barras" Type="articulo" IsForeignKey="true" />
      <Association Name="inventario_fisico_inventario_captura" Member="inventario_fisico" ThisKey="id_inventario_fisico" OtherKey="id_inventario_fisico" Type="inventario_fisico" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.inventario_fisico" Member="inventario_fisico">
    <Type Name="inventario_fisico">
      <Column Name="id_inventario_fisico" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_proveedor" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_ini" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_fin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="inventario_fisico_inventario_captura" Member="inventario_captura" ThisKey="id_inventario_fisico" OtherKey="id_inventario_fisico" Type="inventario_captura" />
      <Association Name="proveedor_inventario_fisico" Member="proveedor" ThisKey="id_proveedor" OtherKey="id_proveedor" Type="proveedor" IsForeignKey="true" />
      <Association Name="usuario_inventario_fisico" Member="usuario" ThisKey="user_name" OtherKey="user_name" Type="usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.orden" Member="orden">
    <Type Name="orden">
      <Column Name="id_pedido" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="num_pedido" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="fecha_pedido" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id_proveedor" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="status_pedido" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="no_dias" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="fecha_autorizado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[plan]" Member="plan" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="anio" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="mes" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="orden_orden_articulo" Member="orden_articulo" ThisKey="id_pedido" OtherKey="id_pedido" Type="orden_articulo" />
      <Association Name="proveedor_orden" Member="proveedor" ThisKey="id_proveedor" OtherKey="id_proveedor" Type="proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.orden_articulo" Member="orden_articulo">
    <Type Name="orden_articulo">
      <Column Name="id_pedido" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="no_articulo" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cod_barras" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="cod_anexo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="precio_articulo" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="por_surtir" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="por_surtir_pzas" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="orden_orden_articulo" Member="orden" ThisKey="id_pedido" OtherKey="id_pedido" Type="orden" IsForeignKey="true" />
      <Association Name="articulo_orden_articulo" Member="articulo" ThisKey="cod_anexo" OtherKey="cod_barras" Type="articulo" IsForeignKey="true" />
      <Association Name="articulo_orden_articulo1" Member="articulo1" ThisKey="cod_barras" OtherKey="cod_barras" Type="articulo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.proveedor" Member="proveedor">
    <Type Name="proveedor">
      <Column Name="id_proveedor" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rfc" Type="System.String" DbType="VarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="razon_social" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_contacto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tel_principal" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="tel_movil" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="e_mail" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="estatus" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="proveedor_articulo" Member="articulo" ThisKey="id_proveedor" OtherKey="id_proveedor" Type="articulo" />
      <Association Name="proveedor_compra" Member="compra" ThisKey="id_proveedor" OtherKey="id_proveedor" Type="compra" />
      <Association Name="proveedor_inventario_fisico" Member="inventario_fisico" ThisKey="id_proveedor" OtherKey="id_proveedor" Type="inventario_fisico" />
      <Association Name="proveedor_orden" Member="orden" ThisKey="id_proveedor" OtherKey="id_proveedor" Type="orden" />
    </Type>
  </Table>
  <Table Name="dbo.unidad_medida" Member="unidad_medida">
    <Type Name="unidad_medida">
      <Column Name="id_unidad" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="cve_sat" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="unidad_medida_articulo" Member="articulo" ThisKey="id_unidad" OtherKey="id_unidad" Type="articulo" />
    </Type>
  </Table>
  <Table Name="dbo.usuario" Member="usuario">
    <Type Name="usuario">
      <Column Name="user_name" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_usuario" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="enable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="user_code_bascula" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="usuario_inventario_fisico" Member="inventario_fisico" ThisKey="user_name" OtherKey="user_name" Type="inventario_fisico" />
      <Association Name="usuario_usuario_permiso" Member="usuario_permiso" ThisKey="user_name" OtherKey="user_name" Type="usuario_permiso" />
    </Type>
  </Table>
  <Table Name="dbo.usuario_permiso" Member="usuario_permiso">
    <Type Name="usuario_permiso">
      <Column Name="user_name" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_permiso" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="valor_num" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="usuario_usuario_permiso" Member="usuario" ThisKey="user_name" OtherKey="user_name" Type="usuario" IsForeignKey="true" />
    </Type>
  </Table>
</Database>